apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: educplatform
  labels:
    app-label: educplatform
spec:
  ports:
    - port: 8081
      name: plaintext
      targetPort: 8081
  selector:
    app-label: educplatform
  type: LoadBalancer
