server:
  port: 8081

spring:
  application:
    name: educplatform-security

  config:
    import: optional:file:.env[.properties]

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        integrator_provider: ru.rtstudy.educplatformsecurity.config.ClassImportIntegratorProvider

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yml


jwt:
  secretKey: gfjnkdjgf234234jn2340v8uUNdiFasd4vfeSDSkjvdfggdadg5t53461gradf

