spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local

educplatform:
  uri: http://localhost:8081/api/v1/auth/

server:
  port: 8082

cloud:
  aws:
    credentials:
      access-key: YCAJEHbENc21rOfoFaIovtS5M
      secret-key: YCNbwM49Sje3glE3NOjynywwRYF-aVEEzDTTpy7l
amazonS3:
  bucket-name: rtischool-store
---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8082

educplatform:
  uri: http://158.160.143.166:8081/api/v1/auth/

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

amazonS3:
  bucket-name: ${BUCKET_NAME}

s3ServiceURI: http://158.160.149.227:8082/object/