spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local

  minio:
    url: http://localhost:9000
    access-key: java
    secret-key: password
    bucket: educplatform

educplatform:
  uri: http://localhost:8081/api/v1/auth/
server:
  port: 8082

amazonS3:
  bucket-name: rtischool-store
---
spring:
  config:
    activate:
      on-profile: dev

  minio:
    url: play.min.io
    access-key: Q3AM3UQ867SPQQA43P2F
    secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    bucket: educplatform

server:
  port: 8082

educplatform:
  uri: http://158.160.143.166:8081/api/v1/auth/

amazonS3:
  bucket-name: ${BUCKET_NAME}