spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local

  minio:
    url: http://localhost:9000
    access-key: java
    secret-key: password
    bucket: educplatform

educplatform:
  uri: http://localhost:8081/api/v1/auth/
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev

  minio:
    url: http://minio:9000
    access-key: java
    secret-key: password
    bucket: educplatform

server:
  port: 8082

educplatform:
  uri: http://education-platform:8081/api/v1/auth/